"""Init

Revision ID: b43b245e0d7e
Revises: 
Create Date: 2023-03-12 22:10:32.444088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43b245e0d7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastupdate', sa.DateTime(), nullable=True),
    sa.Column('folder_root', sa.Text(), nullable=False),
    sa.Column('folder_link', sa.Text(), nullable=False),
    sa.Column('folder_short', sa.Text(), nullable=False),
    sa.Column('folder_name', sa.Text(), nullable=False),
    sa.Column('rgf', sa.String(length=255), nullable=False),
    sa.Column('tgf_hmao', sa.String(length=255), nullable=False),
    sa.Column('tgf_ynao', sa.String(length=255), nullable=False),
    sa.Column('tgf_kras', sa.String(length=255), nullable=False),
    sa.Column('tgf_ekat', sa.String(length=255), nullable=False),
    sa.Column('tgf_omsk', sa.String(length=255), nullable=False),
    sa.Column('tgf_novo', sa.String(length=255), nullable=False),
    sa.Column('tgf_more', sa.String(length=255), nullable=False),
    sa.Column('tgf_tmn', sa.String(length=255), nullable=False),
    sa.Column('tgf', sa.String(length=255), nullable=False),
    sa.Column('report_name', sa.Text(), nullable=False),
    sa.Column('author_name', sa.Text(), nullable=False),
    sa.Column('year_str', sa.String(length=255), nullable=False),
    sa.Column('year_int', sa.Integer(), nullable=False),
    sa.Column('territory_name', sa.Text(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='adoc'
    )
    op.create_index(op.f('ix_adoc_adoc_author_name'), 'adoc', ['author_name'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_comments'), 'adoc', ['comments'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_folder_link'), 'adoc', ['folder_link'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_folder_name'), 'adoc', ['folder_name'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_folder_root'), 'adoc', ['folder_root'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_folder_short'), 'adoc', ['folder_short'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_rgf'), 'adoc', ['rgf'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_territory_name'), 'adoc', ['territory_name'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_tgf'), 'adoc', ['tgf'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_tgf_ekat'), 'adoc', ['tgf_ekat'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_tgf_hmao'), 'adoc', ['tgf_hmao'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_tgf_kras'), 'adoc', ['tgf_kras'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_tgf_more'), 'adoc', ['tgf_more'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_tgf_novo'), 'adoc', ['tgf_novo'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_tgf_omsk'), 'adoc', ['tgf_omsk'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_tgf_tmn'), 'adoc', ['tgf_tmn'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_tgf_ynao'), 'adoc', ['tgf_ynao'], unique=False, schema='adoc')
    op.create_index(op.f('ix_adoc_adoc_year_str'), 'adoc', ['year_str'], unique=False, schema='adoc')
    op.create_table('adoc_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastupdate', sa.DateTime(), nullable=True),
    sa.Column('file_in', sa.String(length=255), nullable=False),
    sa.Column('file_out', sa.String(length=255), nullable=False),
    sa.Column('file_out_path', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='adoc'
    )
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastupdate', sa.DateTime(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='adoc'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author', schema='adoc')
    op.drop_table('adoc_history', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_year_str'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_tgf_ynao'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_tgf_tmn'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_tgf_omsk'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_tgf_novo'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_tgf_more'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_tgf_kras'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_tgf_hmao'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_tgf_ekat'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_tgf'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_territory_name'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_rgf'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_folder_short'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_folder_root'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_folder_name'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_folder_link'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_comments'), table_name='adoc', schema='adoc')
    op.drop_index(op.f('ix_adoc_adoc_author_name'), table_name='adoc', schema='adoc')
    op.drop_table('adoc', schema='adoc')
    # ### end Alembic commands ###
