# Базу создавать так
CREATE USER adoc WITH ENCRYPTED PASSWORD 'adocpwd';
CREATE DATABASE adoc WITH OWNER adoc;
GRANT ALL PRIVILEGES ON DATABASE adoc TO adoc;
\c adoc;
CREATE SCHEMA IF NOT EXISTS adoc AUTHORIZATION adoc;
SET search_path to adoc;

# Возможно пригодиться
# GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO adoc;
# GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO adoc;
# GRANT ALL PRIVILEGES ON ALL FUNCTIONS  IN SCHEMA public TO adoc;